# Generated by Django 4.2.7 on 2023-11-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
